# Generated by Django 3.2 on 2023-06-05 15:32

from django.db import migrations, models
import mainapp.validators


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_product_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='timestamp',
            field=models.DateField(blank=True, null=True, validators=[mainapp.validators.validate_timestamp]),
        ),
    ]
